#!/usr/bin/env python

from requests import post
from uuid import uuid4
import json

headers = {
  'warehouseKey': 'http://devportal.suppliesnet.net|lx85dFdineQZ5GfE|nopass',
  'clientRef': 'kittydemo',
  'Content-Type': 'application/json',
  'Authorization': 'Basic U3ltcGhvbnlBUEk6c3pFc1ExOWlCVW9KTXVFYW82eWo4bWp3Q1RBcW40elB2anJvUFREeg=='
}

while True:
  response = post('http://localhost:1234/api/v1/shipments', headers = headers, json = {
   "symphonyShipmentId": str(uuid4()),
   "purchaseOrder": "PO1234",
   "createdDate": "2015-02-15T00:00:00",
   "reference1": "Ref1234",
   "reference2": "",
   "warehouse": "DM_MO_STL1",
   "notes": "",
   "shippingAddress": {
     "firstName": "Steve",
     "lastName": "Xian",
     "street1": "1045 Bryant Street",
     "street2": "suite 200",
     "city": "San Francisco",
     "state": "CA",
     "country": "United States",
     "zip": "94103",
     "email": "targetwholesale@target.com",
     "phone": "8057002000",
     "company": ""
   },
   "shippingMethod": "FEDEX.2DAY.SHIPPING",
   "thirdPartyAccountNumber": "1234567890ABCD",
   "lineItems": [
     {
       "sku": "BIG MONEY",
       "quantity": 1
     }
   ]
  })

  print response